"""N-of-M signal voting — combine ML signal with rule-based conditions.

Column names verified against:
  features/technical_features.py  -> btc_trend_score, btc_rsi14_ob, btc_vol_ma_ratio_14d
  features/regime_features.py     -> btc_regime_bear, btc_regime_sideways
  features/cross_asset_features.py-> btc_SPY_corr_30d (actual: btc_SPY_corr_30d)
  data/fetch_onchain.py           -> fg_value (fear & greed)
  data/fetch_stocks.py VIX        -> ^VIX_ret_1d / vix_zscore in build_features

Fix: replaced all mismatched column names with verified actual names.
"""
import pandas as pd
import numpy as np
from loguru import logger
from config import CFG


def build_multi_signal(
    df: pd.DataFrame,
    model_signal: pd.Series,
    n_required: int | None = None,
) -> tuple[pd.Series, pd.DataFrame]:
    """
    Combine ML signal with rule-based conditions.
    Each sub-signal = +1 (long) or 0 (not long).
    Final signal fires:
      +1  if vote_count >= n_required
      -1  if vote_count < (total - n_required)  [strong disagreement]
       0  otherwise
    """
    sub_signals: dict = {}

    # 1. ML model signal
    sub_signals["ml_signal"] = (model_signal == 1).astype(int)

    # 2. BTC trend score >= 2 (at least 2 of 3 EMAs bullish)
    # generated by technical_features.py: btc_trend_score (0-3 EMA alignment)
    if "btc_trend_score" in df.columns:
        sub_signals["trend_bullish"] = (df["btc_trend_score"] >= 2).astype(int)
    else:
        logger.warning("btc_trend_score not found; skipping trend_bullish sub-signal")

    # 3. BTC not in bear regime
    # generated by regime_features.py: btc_regime_bear (0/1)
    if "btc_regime_bear" in df.columns:
        sub_signals["not_bear_regime"] = (1 - df["btc_regime_bear"]).astype(int)
    else:
        logger.warning("btc_regime_bear not found; skipping not_bear_regime sub-signal")

    # 4. BTC not in sideways regime (confirm directional move)
    # generated by regime_features.py: btc_regime_sideways (0/1)
    if "btc_regime_sideways" in df.columns:
        sub_signals["not_sideways"] = (1 - df["btc_regime_sideways"]).astype(int)
    else:
        logger.warning("btc_regime_sideways not found; skipping not_sideways sub-signal")

    # 5. Fear & Greed not extreme greed (avoid FOMO tops)
    # generated by fetch_onchain.py: column name is 'fg_value'
    if "fg_value" in df.columns:
        sub_signals["fg_not_extreme_greed"] = (df["fg_value"] < 75).astype(int)
    else:
        logger.warning("fg_value not found; skipping fg sub-signal")

    # 6. BTC-SPY rolling 30d correlation > 0.3 (risk-on regime)
    # generated by cross_asset_features.py: btc_SPY_corr_30d
    corr_col = "btc_SPY_corr_30d"
    if corr_col in df.columns:
        sub_signals["risk_on_corr"] = (df[corr_col] > 0.3).astype(int)
    else:
        logger.warning(f"{corr_col} not found; skipping risk_on_corr sub-signal")

    # 7. BTC RSI14 not overbought
    # generated by technical_features.py: btc_rsi14_ob (0/1 flag)
    if "btc_rsi14_ob" in df.columns:
        sub_signals["rsi_not_ob"] = (1 - df["btc_rsi14_ob"]).astype(int)
    else:
        logger.warning("btc_rsi14_ob not found; skipping rsi_not_ob sub-signal")

    # 8. Volume surge (momentum confirmation)
    # generated by technical_features.py / volatility_features.py:
    # try 14d ratio first, then 7d fallback
    vol_col = "btc_vol_ma_ratio_14d" if "btc_vol_ma_ratio_14d" in df.columns else "btc_vol_ma_ratio_7d"
    if vol_col in df.columns:
        sub_signals["vol_surge"] = (df[vol_col] > 1.2).astype(int)
    else:
        logger.warning("btc_vol_ma_ratio_*d not found; skipping vol_surge sub-signal")

    # 9. risk_on_score composite (cross-asset)
    # generated by cross_asset_features.py: risk_on_score (0-1 percentile rank)
    if "risk_on_score" in df.columns:
        sub_signals["risk_on_score"] = (df["risk_on_score"] > 0.5).astype(int)
    else:
        logger.warning("risk_on_score not found; skipping risk_on_score sub-signal")

    # ------------------------------------------------------------------
    signal_df = pd.DataFrame(sub_signals, index=df.index)
    n_total = len(sub_signals)

    # Dynamic n_required
    if n_required is None:
        if n_total >= 7:
            n_required = CFG.n_of_m_threshold   # default = 3
        elif n_total >= 5:
            n_required = 3
        elif n_total >= 3:
            n_required = 2
        else:
            n_required = 1

    vote_counts = {k: int(v.sum()) for k, v in sub_signals.items()}
    logger.info(
        f"multi_signal: {n_total} sub-signals, requiring {n_required} to fire.\n"
        f"  Vote counts: {vote_counts}"
    )

    vote_count = signal_df.sum(axis=1)
    final_signal = pd.Series(0, index=df.index)
    final_signal[vote_count >= n_required] = 1
    final_signal[vote_count < (n_total - n_required)] = -1

    pos = (final_signal == 1).sum()
    neg = (final_signal == -1).sum()
    logger.info(f"  Final signal: long={pos}, short={neg}, flat={len(final_signal)-pos-neg}")

    return final_signal, signal_df
