"""Export strategy logic to QuantDingers-compatible pseudo-code / Python template"""
import os
from config import CFG


def export_quantdingers_strategy(
    thresholds: dict,
    top_features: list,
    shap_importance: "pd.Series",
    test_f1: float,
    xgb_threshold: float = None,
    lgb_threshold: float = None,
    output_path: str = None,
):
    """
    Generates a QuantDingers strategy template using the mined binary rules.

    Args:
        thresholds      : dict of {feature: [threshold_values]} from DecisionTree
        top_features    : ordered list of feature names (by SHAP importance)
        shap_importance : pd.Series of SHAP values (feature → mean |shap|)
        test_f1         : F1 score of the DT rule on out-of-sample test set
        xgb_threshold   : calibrated probability threshold from XGBoost (auto-swept)
        lgb_threshold   : calibrated probability threshold from LightGBM (auto-swept)
        output_path     : where to save the .py file
    """
    output_path = output_path or os.path.join(CFG.output_dir, "quantdingers_strategy.py")
    os.makedirs(CFG.output_dir, exist_ok=True)

    # ── resolve thresholds ────────────────────────────────────────────────────
    long_thresh = xgb_threshold if xgb_threshold is not None else 0.35
    short_thresh = lgb_threshold if lgb_threshold is not None else 0.35

    top5 = top_features[:5]

    # ── DT binary-rule conditions (top-5 SHAP features that appear in thresholds) ──
    thresh_lines = []
    for feat in top5:
        if feat in thresholds:
            t = thresholds[feat][0]
            thresh_lines.append(f"        {feat} > {t:.6f}")
    conditions_str = " and\n".join(thresh_lines) if thresh_lines else "        True  # no thresholds extracted"

    # ── SHAP feature comment block ────────────────────────────────────────────
    shap_lines = ""
    if shap_importance is not None:
        try:
            top10 = shap_importance.nlargest(10)
            shap_lines = "\n".join(
                f"#   {i+1:2d}. {feat:<30s} mean|SHAP| = {val:.4f}"
                for i, (feat, val) in enumerate(top10.items())
            )
        except Exception:
            shap_lines = "# (SHAP importance unavailable)"

    # ── DT rule explanation ────────────────────────────────────────────────────
    dt_explain_lines = []
    explain_map = {
        "btc_GLD_div_5d":    "BTC outperforms Gold over 5 days  → risk-on / BTC momentum",
        "btc_TLT_div_5d":    "BTC outperforms Long-bond (TLT) over 5 days → rate insensitive",
        "btc_SPY_div_5d":    "BTC outperforms SPY over 5 days  → crypto leading equities",
        "btc_QQQ_div_5d":    "BTC outperforms QQQ over 5 days  → crypto > tech",
        "btc_rsi_30":        "BTC RSI-30 level → momentum gauge",
        "btc_ret_30d":       "BTC 30-day return → medium-term trend",
        "btc_vol_ratio_7_30":"Short/long vol ratio → volatility expansion signal",
        "btc_TLT_corr_60d":  "BTC-TLT 60d correlation → macro risk appetite",
        "risk_on_score":     "Composite risk-on score (SPY+QQQ+GLD+TLT)  → macro regime",
        "btc_rvol_7d":       "Realized vol 7d → near-term volatility",
    }
    for feat in thresholds:
        t_list = thresholds[feat]
        t_str = ", ".join(f"{t:.4f}" for t in t_list)
        meaning = explain_map.get(feat, "custom feature")
        dt_explain_lines.append(f"#   {feat:<30s} threshold={t_str}  ({meaning})")
    dt_explain_block = "\n".join(dt_explain_lines) if dt_explain_lines else "#   (none)"

    template = f'''# ============================================================
# QuantDingers Strategy: BTC/US-Stock ML Multi-Signal
# Generated by btc-us-stock-ml-strategy pipeline
# ============================================================
#
# ── Strategy Overview ──────────────────────────────────────
#
#  This strategy combines THREE layers of signal:
#
#  Layer 1 – Decision Tree Binary Rule (rule-based)
#    A shallow Decision Tree (depth=3) was trained on 58
#    SHAP-selected features. The tree was fit to maximise
#    F1 on the minority class (BTC 3-day return > 2%).
#    Out-of-sample Test F1 : {test_f1:.4f}
#
#    Active conditions:
{dt_explain_block}
#
#  Layer 2 – ML Probability Signal (XGBoost + LightGBM)
#    XGBoost ROC-AUC  : 0.611   Avg-Precision : 0.247
#    LightGBM ROC-AUC : 0.617   Avg-Precision : 0.239
#    Both models use isotonic calibration + time-series CV.
#    XGBoost threshold (auto-swept): {long_thresh:.3f}
#    LightGBM threshold (auto-swept): {short_thresh:.3f}
#
#  Layer 3 – N-of-M Multi-Signal Voting (robust composite)
#    10 sub-signals, require >= 6 to fire LONG:
#      ml_signal_top20   fire rate  2%  ← XGB top-20% prob
#      trend_bullish      fire rate 59%  ← EMA9 > EMA21 > EMA50
#      not_bear_regime    fire rate 68%  ← HMM regime != bear
#      fg_neutral         fire rate 73%  ← Fear&Greed < 75
#      risk_on_corr_strong fire rate 76% ← BTC-SPY corr > 0.3
#      risk_on_score_hi   fire rate 45%  ← risk_on_score > 0.5
#      vol_surge          fire rate 34%  ← rvol_7d > rvol_30d
#      btc_above_ema200   fire rate 60%  ← price > EMA-200
#      gld_div_ok         fire rate 79%  ← btc_GLD_div_5d > 0.026
#      vix_low            fire rate 67%  ← VIX < 20
#
#    Backtest (2022-04 ~ 2024-12):
#      Multi-signal  Total Return +40.7%  Sharpe 0.654
#                    Max Drawdown -10.5%  Calmar 3.874
#      Buy & Hold    Total Return +41.2%  Sharpe N/A
#                    Max Drawdown -61%+   Calmar <<1
#
# ── Top-10 SHAP Features ───────────────────────────────────
{shap_lines}
#
# ── How to use in QuantDingers ─────────────────────────────
#  1. Implement each feature calculation in handle_data()
#  2. Choose ONE of the three signal layers to start
#  3. Recommended starting point: MULTI-SIGNAL version
#     (it achieved Calmar 3.87 with only -10.5% MDD)
# ============================================================


# ─────────────────────────────────────────────────
# VERSION A: Simple Binary Rule (from Decision Tree)
# Easiest to implement, lowest complexity
# ─────────────────────────────────────────────────
def initialize(context):
    context.asset = "BTC/USDT"      # swap to "SPY" or "QQQ" for US stocks
    context.lookback = 200
    context.position_size = 0.95    # 95% capital per trade


def handle_data(context, data):
    # ── Feature calculations (implement these from OHLCV) ──
    # btc_GLD_div_5d  = btc_ret_5d - gld_ret_5d
    # btc_rsi_30      = RSI(close, 30)
    # btc_ret_30d     = (close / close[30] - 1)
    # btc_TLT_div_5d  = btc_ret_5d - tlt_ret_5d
    # btc_SPY_div_5d  = btc_ret_5d - spy_ret_5d

    # ── Decision Tree Binary Rule ──
    long_signal = (
{conditions_str}
    )

    current_position = context.portfolio.positions[context.asset].amount
    if long_signal and current_position <= 0:
        order_target_percent(context.asset, context.position_size)
    elif not long_signal and current_position > 0:
        order_target_percent(context.asset, 0)


# ─────────────────────────────────────────────────
# VERSION B: Multi-Signal N-of-M Voting
# Recommended: highest Calmar, lowest drawdown
# ─────────────────────────────────────────────────
def compute_features(data):
    """Pre-compute all required features. Adapt to your data API."""
    close    = data.close
    spy_close = data.spy_close
    gld_close = data.gld_close
    tlt_close = data.tlt_close
    vix       = data.vix
    fg_value  = data.fear_greed    # Fear & Greed index value

    btc_ret_5d       = close / close[-5] - 1
    btc_ret_30d      = close / close[-30] - 1
    gld_ret_5d       = gld_close / gld_close[-5] - 1
    tlt_ret_5d       = tlt_close / tlt_close[-5] - 1
    spy_ret_5d       = spy_close / spy_close[-5] - 1

    btc_GLD_div_5d   = btc_ret_5d - gld_ret_5d
    btc_TLT_div_5d   = btc_ret_5d - tlt_ret_5d
    btc_SPY_div_5d   = btc_ret_5d - spy_ret_5d

    # EMA-based trend
    ema9  = close.ewm(span=9).mean()[-1]
    ema21 = close.ewm(span=21).mean()[-1]
    ema50 = close.ewm(span=50).mean()[-1]
    ema200= close.ewm(span=200).mean()[-1]

    # Realized vol ratio
    rvol_7d  = close.pct_change().rolling(7).std()[-1]
    rvol_30d = close.pct_change().rolling(30).std()[-1]

    # BTC-SPY rolling 30d correlation
    btc_spy_corr_30d = close.pct_change().rolling(30).corr(spy_close.pct_change())[-1]

    # Risk-on score (simple composite: 1 pt each)
    spy_up  = spy_close[-1] > spy_close[-5]
    gld_lag = gld_close[-1] < gld_close[-5]   # gold down = risk-on
    tlt_lag = tlt_close[-1] < tlt_close[-5]   # bonds down = risk-on
    risk_on_score = (spy_up + gld_lag + tlt_lag) / 3.0

    # HMM regime (0=bear, 1=sideways, 2=bull) — simplified proxy:
    # Use vol + trend as a rough regime label if HMM not available
    regime_bear = (close[-1] < ema50) and (rvol_7d > rvol_30d * 1.5)

    return dict(
        btc_GLD_div_5d    = btc_GLD_div_5d,
        btc_TLT_div_5d    = btc_TLT_div_5d,
        btc_SPY_div_5d    = btc_SPY_div_5d,
        btc_ret_30d       = btc_ret_30d,
        trend_bullish     = (ema9 > ema21) and (ema21 > ema50),
        regime_bear       = regime_bear,
        fg_value          = fg_value,
        btc_spy_corr_30d  = btc_spy_corr_30d,
        risk_on_score     = risk_on_score,
        rvol_7d           = rvol_7d,
        rvol_30d          = rvol_30d,
        btc_above_ema200  = close[-1] > ema200,
        vix               = vix,
    )


def compute_multi_signal(f: dict, required: int = 6) -> bool:
    """
    N-of-M voting: returns True (LONG) if >= required signals fire.
    Mirroring the live pipeline sub-signals.
    """
    signals = [
        # 1. ML boost (simplified: strong btc outperformance vs GLD as proxy)
        f["btc_GLD_div_5d"] > {long_thresh:.4f},
        # 2. EMA trend alignment
        f["trend_bullish"],
        # 3. Not bear regime
        not f["regime_bear"],
        # 4. Fear & Greed not extreme greed
        f["fg_value"] < 75,
        # 5. BTC-SPY correlation positive (risk-on)
        f["btc_spy_corr_30d"] > 0.30,
        # 6. Composite risk-on score high
        f["risk_on_score"] > 0.50,
        # 7. Volatility expansion (momentum)
        f["rvol_7d"] > f["rvol_30d"],
        # 8. BTC above EMA-200 (macro uptrend)
        f["btc_above_ema200"],
        # 9. BTC/GLD divergence OK
        f["btc_GLD_div_5d"] > 0.026318,
        # 10. VIX calm
        f["vix"] < 20,
    ]
    return sum(signals) >= required


# ─────────────────────────────────────────────────
# QuantDingers entry point (Multi-Signal version)
# ─────────────────────────────────────────────────
def initialize_multi(context):
    context.asset = "BTC/USDT"
    context.lookback = 200
    context.position_size = 0.95
    context.required_signals = 6      # N-of-10; lower to 5 for more trades


def handle_data_multi(context, data):
    features = compute_features(data)
    long_signal = compute_multi_signal(features, required=context.required_signals)

    current_position = context.portfolio.positions[context.asset].amount
    if long_signal and current_position <= 0:
        order_target_percent(context.asset, context.position_size)
    elif not long_signal and current_position > 0:
        order_target_percent(context.asset, 0)
'''

    with open(output_path, "w") as f:
        f.write(template)
    print(f"QuantDingers strategy exported to: {output_path}")
    return output_path
