"""Export strategy logic to QuantDingers-compatible pseudo-code / Python template"""
import os
from config import CFG

def export_quantdingers_strategy(
    thresholds: dict,
    top_features: list,
    shap_importance: "pd.Series",
    test_f1: float,
    output_path: str = None,
):
    """
    Generates a QuantDingers strategy template using the mined binary rules.
    The template can be pasted directly into QuantDingers strategy editor.
    """
    output_path = output_path or os.path.join(CFG.output_dir, "quantdingers_strategy.py")
    os.makedirs(CFG.output_dir, exist_ok=True)

    top5 = top_features[:5]
    thresh_lines = []
    for feat in top5:
        if feat in thresholds:
            t = thresholds[feat][0]
            thresh_lines.append(f"    {feat} > {t:.6f}")

    conditions_str = " and\n".join(thresh_lines) if thresh_lines else "    True  # no thresholds extracted"

    template = f'''# ============================================================
# QuantDingers Strategy: BTC/US Stock ML Binary Rule
# Generated by btc-us-stock-ml-strategy pipeline
# Test F1 Score: {test_f1:.4f}
# Top Features (by SHAP): {top5}
# ============================================================

# --- SIGNAL LOGIC ---
# This strategy uses a Decision Tree-derived binary rule.
# Each condition corresponds to a feature threshold
# extracted from the best-performing shallow Decision Tree.

def initialize(context):
    context.asset = "BTC/USDT"  # or SPY, QQQ
    context.lookback = 200
    context.position_size = 0.95
    context.long_threshold = {CFG.long_prob_threshold}
    context.short_threshold = {CFG.short_prob_threshold}

def handle_data(context, data):
    # --- Compute features ---
    # (map each feature name to its calculation)
    # Features below should be pre-computed from OHLCV:
    # {chr(10).join([f"    # {f}" for f in top5])}

    # --- Binary Rule (from Decision Tree) ---
    # Rule test F1 on out-of-sample: {test_f1:.4f}
    long_signal = (
{conditions_str}
    )

    # --- Position Management ---
    current_position = context.portfolio.positions[context.asset].amount

    if long_signal and current_position <= 0:
        order_target_percent(context.asset, context.position_size)
    elif not long_signal and current_position > 0:
        order_target_percent(context.asset, 0)

# --- MULTI-SIGNAL VERSION (N-of-M voting) ---
# Uncomment and adapt for a more robust signal:
#
# def compute_multi_signal(features):
#     signals = [
#         features["ml_prob"] > {CFG.long_prob_threshold},       # ML model
#         features["btc_trend_score"] >= 2,                      # EMA alignment
#         features["vix_low"] == 1,                              # VIX calm
#         features["btc_regime_bear"] == 0,                      # Not bear regime
#         features["fg_value"] < 75,                             # Not extreme greed
#     ]
#     return sum(signals) >= 3  # N-of-5
'''

    with open(output_path, "w") as f:
        f.write(template)
    print(f"QuantDingers strategy exported to: {output_path}")
    return output_path
